#!/bin/sh
# 
# everything is tied up to VERSION_DIR directory
#
VERSION_DIR=/develop/home/vgael/_trunk
EXE_DIR=$VERSION_DIR/LINUX_GCC_4_3_64

# hybrid looks for its files in subdirectories if NUMECA_DIR
NUMECA_DIR=$VERSION_DIR
export NUMECA_DIR

# shared liibraries for hybrid
LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:$EXE_DIR/_lib_s:$EXE_DIR/_lib_s/_dtk2014.2:$EXE_DIR/_lib_s/_netcdf-4.1.3
export LD_LIBRARY_PATH

# full path to hybrid executable
#HYB_VERSION=$EXE_DIR/_bin/hexpresshybrid
HYB_VERSION=hexpresshybridopen51a0

# location of the test script
#SCRIPT_DIR=/develop/tests/hybrid/_runs
SCRIPT_DIR=.

# location of the database
DB_dir="/develop/tests/hybrid/_test_cases"
#DB_dir="/develop/tests/hybrid/_test_cases_QA"
#DB_dir="/develop/tests/hybrid/_test_cases_QA_full_hexa"
#DB_dir="/develop/tests/hybrid/_testCasesThinWalls"

# location of the test lists
#LIST_DIR=/develop/tests/hybrid/_runs
LIST_DIR=.

# possibility to estend configuration file
CONF_MODIFY=""
#CONF_MODIFY+="DEBUGLEVEL-3-\n-\n"

# output directory
#OUT_DIR=""
OUT_DIR="TEST_RESULTS"

# number of cores
NUMPROC=12


